### ISSUE TITLE
Event Status Constants

### ISSUE THREAD

**Issue by wendelfreitas** [leonardomso/roover#254]
Maybe is a good alternative create constants to manage this data

like a file with all exported constants 

```js
//src/utils/constants.ts

export default { 
 PAUSE: 'PAUSE'
}

//src/hooks/useRoover/useRoover.ts

import ROOVER from 'utils/constants'; 

service.send(ROOVER.PAUSE);

```

https://github.com/leonardomso/roover/blob/127a9b0a34c21107faf2a0bb370802746c583031/src/hooks/useRoover/useRoover.ts#L147

What do you think @leonardomso ?

**Comment by leonardomso** [comment]
I'm not sure if it would make sense to create a new file with event constants. Right now, we have the `MachineEvent` type for all the events that we can possibly have on our finite state machine. If we try to invoke a event that's not one of the events in `MachineEvent` type it would throw an error.

https://github.com/leonardomso/roover/blob/3c9e315997f0e242e658b6a1791fcc4bba7ac5c9/src/machine/Machine.types.ts#L26-L38

**Comment by leonardomso** [comment]
Anyway, the #255 was merge with the constants file. We can leave it as it is for now.
